### ISSUE TITLE
Game load stuck on awe.json

### ISSUE THREAD

**Issue by psycho202** [zlsa/atc#41]
Loading http://zlsa.github.io/atc/
Stuck on loading awe.json

Console: 
"[ INFO  ]" "Version v2.1.7" modules.js:124
"[ INFO  ]" "Finished loading 13 modules in 0.079s" modules.js:124
"[ WARN  ]" "Failed to get assets/airlines/awe.json: 0"

**Comment by zlsa** [comment]
It's caused by an adblocker... apparently AWE is in a keyword list somewhere. I'll remove AWE for now but I'll need to find a way around this.

**Comment by psycho202** [comment]
Confirmed. Turning off Adblock Plus removes the issue.

**Comment by zlsa** [comment]
It's also been commented out as no airport uses the US Airways airline yet.

**Comment by zlsa** [comment]
EasyList blocks `awe.js` (and presumably `awe.json` as well); I'll contact them and see if I can resolve it.

**Comment by zlsa** [comment]
This has been fixed in the latest version of EasyList: http://forums.lanik.us/viewtopic.php?f=64&t=20074

**Comment by Diastro** [comment]
Wow that was quick :+1:

**Comment by Diastro** [comment]
For anyonw still unable to load the page : 
- Click on the addblock icon (next to the adress bar on Chrome)
- Options
- Click update now which will update EasyList

Should work then
